export const algorithms = [
    {
      title: 'Divide and Conquer',
      algorithms: [
        'Bucket Sort',
        'Counting Sort',
        'Merge Sort',
        'Pigeonhole Sort',
        'Quicksort',
        'Radix Sort',
        'Binary Search',
        'Strassen\'s Matrix Multiplication',
        'Closest Pair of Points',
        'Convex Hull',
      ],
    },
    {
      title: 'Dynamic Programming',
      algorithms: [
        'Bellman-Ford\'s Shortest Path',
        'Catalan Number',
        'Fibonacci Sequence',
        'Floyd-Warshall\'s Shortest Path',
        'Integer Partition',
        'Knapsack Problem',
        'Knuth-Morris-Pratt\'s String Search',
        'Levenshtein\'s Edit Distance',
        'Longest Common Subsequence',
        'Longest Increasing Subsequence',
        'Longest Palindromic Subsequence',
        'Maximum Subarray',
        'Maximum Sum Path',
        'Nth Factorial',
        'Pascal\'s Triangle',
        'Shortest Common Supersequence',
        'Sieve of Eratosthenes',
        'Sliding Window',
        'Ugly Numbers',
        'Z String Search',
        'Matrix Chain Multiplication',
        'Edit Distance',
        'Coin Change Problem',
        'Subset Sum Problem',
        'Game Theory (Nim Game, Grundy Numbers)',
      ],
    },
    {
      title: 'Greedy',
      algorithms: [
        'Boyer–Moore\'s Majority Vote',
        'Dijkstra\'s Shortest Path',
        'Job Scheduling Problem',
        'Kruskal\'s Minimum Spanning Tree',
        'Prim\'s Minimum Spanning Tree',
        'Stable Matching',
        'Huffman Coding',
        'Activity Selection Problem',
        'Fractional Knapsack Problem',
        'Change-Making Problem',
      ],
    },
    {
      title: 'Simple Recursive',
      algorithms: [
        'Cellular Automata',
        'Cycle Detection',
        'Euclidean Greatest Common Divisor',
        'Nth Factorial',
        'Suffix Array',
        'Recursive Backtracking (e.g., N-Queens Problem, Sudoku Solver)',
      ],
    },
    {
      title: 'Graph Algorithms',
      algorithms: [
        'Depth-First Search (DFS)',
        'Breadth-First Search (BFS)',
        'A* Search Algorithm',
        'Topological Sorting',
        'Tarjan\'s Algorithm (Strongly Connected Components)',
        'Bellman-Ford Algorithm',
        'Johnson\'s Algorithm',
        'Minimum Spanning Tree (Kruskal and Prim)',
        'Floyd-Warshall Algorithm',
      ],
    },
    {
      title: 'Searching Algorithms',
      algorithms: [
        'Linear Search',
        'Binary Search',
        'Interpolation Search',
        'Exponential Search',
        'Fibonacci Search',
      ],
    },
    {
      title: 'Sorting Algorithms',
      algorithms: [
        'Bubble Sort',
        'Insertion Sort',
        'Selection Sort',
        'Shell Sort',
        'Heap Sort',
        'Comb Sort',
        'Tim Sort',
      ],
    },
    {
      title: 'String Algorithms',
      algorithms: [
        'Rabin-Karp Algorithm',
        'Z Algorithm',
        'Aho-Corasick Algorithm',
        'KMP Algorithm',
        'Suffix Tree Construction',
        'Longest Repeated Substring',
      ],
    },
    {
      title: 'Miscellaneous Algorithms',
      algorithms: [
        'Backtracking (e.g., Hamiltonian Cycle)',
        'Randomized Algorithms (e.g., Randomized QuickSort)',
        'Monte Carlo Algorithms',
        'Simulated Annealing',
        'Genetic Algorithms',
      ],
    },
    {
      title: 'Uncategorised',
      algorithms: [
        'Affine Cipher',
        'Caesar Cipher',
        'Freivalds\' Matrix-Multiplication Verification',
        'K-Means Clustering',
        'Magic Square',
        'Maze Generation',
        'Miller-Rabin\'s Primality Test',
        'Shortest Unsorted Continuous Subarray',
        'Conway\'s Game of Life',
      ],
    },
  ];
  